// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZSypvaLuLdMfLkYE87dlHSaUuuZzHKwU',
    appId: '1:482708687219:web:0e4d129c44f33cbdfc5d06',
    messagingSenderId: '482708687219',
    projectId: 'flutter-chat-57af6',
    authDomain: 'flutter-chat-57af6.firebaseapp.com',
    storageBucket: 'flutter-chat-57af6.appspot.com',
    measurementId: 'G-BST2CDN98H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-ADEJdXGvKNZHZuAAYAcNm99-VD0g5w',
    appId: '1:482708687219:android:6649fedc10a05510fc5d06',
    messagingSenderId: '482708687219',
    projectId: 'flutter-chat-57af6',
    storageBucket: 'flutter-chat-57af6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrcbylfb-L4MregY9L4HnO50qs3nakL0',
    appId: '1:482708687219:ios:9d2e4c445c01216afc5d06',
    messagingSenderId: '482708687219',
    projectId: 'flutter-chat-57af6',
    storageBucket: 'flutter-chat-57af6.appspot.com',
    androidClientId: '482708687219-otnjpgh4gci7n5qem46g9thr29n52nu0.apps.googleusercontent.com',
    iosClientId: '482708687219-cs4bvnhrjgenetctj5cqi8kjs5fk94d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );
}
